# Generated by Django 5.2 on 2026-09-26 17:50

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('minimum_age', models.PositiveSmallIntegerField(default=0, verbose_name='Аge restriction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Category create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Category update')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_category', violation_error_message='A category with this name already exists.')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
                ('manufacturer_name', models.CharField(max_length=50, verbose_name='Product manufacturer')),
                ('minimum_age', models.PositiveSmallIntegerField(default=0, verbose_name='Аge restriction')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Product article')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product weight in kilograms')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product height in centimeters')),
                ('color', models.CharField(blank=True, max_length=15, verbose_name='Product color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Product update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'constraints': [models.CheckConstraint(condition=models.Q(('height_cm__gt', 0)), name='height_cm_positive', violation_error_message='The product height must be greater than zero.'), models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='weight_kg_positive', violation_error_message='The weight must be greater than zero.'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_positive', violation_error_message='The product price must be greater than zero.')],
            },
        ),
    ]
