# Generated by Django 5.2 on 2026-10-02 12:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Warehouse name')),
                ('code', models.CharField(max_length=50, verbose_name='Warehouse code')),
                ('address', models.CharField(max_length=255, verbose_name='Warehouse address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Warehouse active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Warehouse create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Warehouse update')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_lower_warehouse_code', violation_error_message='A warehouse with this code already exists.')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Warehouse manager assignment created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse manager assignment',
                'verbose_name_plural': 'Warehouse manager assignments',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'user'), name='unique_user_warehouse_relation', violation_error_message='This user is already assigned to this warehouse.')],
            },
        ),
    ]
