# Generated by Django 5.2 on 2026-10-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Order updated')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_orders', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity product in order')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price in order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order item created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Order item updated')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_0', violation_error_message='Quantity must be greater than 0'), models.UniqueConstraint(fields=('order', 'product'), name='unique_order_item_order_and_product', violation_error_message='This product is already assigned to this order.')],
            },
        ),
    ]
