# Generated by Django 5.2 on 2026-10-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Stock quantity product in warehouse')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Reserved quantity product in warehouse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stock created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Stock updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_stock_warehouse_product', violation_error_message='This product is already assigned to this warehouse.'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_quantity_lte_quantity', violation_error_message="Reserved quantity can't be more than quantity")],
            },
        ),
    ]
